PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.profile, name="profile"),
    path("profile_update/", views.profile_update, name="profile_update"),
    path("delete/", views.delete, name="delete"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("change_password/", views.change_password, name="change_password"),
    path('cart/', views.cart, name='cart'), # 장바구니 페이지
    path('cart/update/', views.cart_update, name='cart_update'), # 장바구니 구매 및 삭제
    path('cart/payment/', views.payment, name='payment'),
    path('<int:product_pk>/ddib_delete/', views.ddib_delete, name='ddib_delete'), # 프로필에서 찜한 상품(product_pk) 삭제
    path('<int:product_pk>/tocart/', views.tocart, name='tocart'), # 찜한 상품 모달에서 수량 선택 후 장바구니로 담기
    path('isValidId/', views.isValidId, name='isValidId'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/ddib/', views.ddib, name='ddib'),
    path('<int:product_pk>/cart/', views.cart, name='cart'),
    path('<int:product_pk>/review_create/', views.review_create, name='review_create'),
    path('<int:product_pk>/<int:review_pk>/review_update/', views.review_update, name='review_update'),
    path('<int:product_pk>/inquiry/', views.create_inquiry, name='create_inquiry'),   # 문의 등록
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/update/', views.update_inquiry, name='update_inquiry'),   # 문의 수정
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/delete/', views.delete_inquiry, name='delete_inquiry'),   # 문의 삭제
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/reply/', views.create_reply, name='create_reply'),   # 답변 등록
    path('<int:product_pk>/payment/', views.payment, name='payment'),
]

products/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=36)
    content = models.CharField(max_length=27)   # 상품 짧은 소개
    carbohydrate = models.FloatField(blank=True)    # 탄수화물
    protein = models.FloatField(blank=True) # 단백질
    fat = models.FloatField(blank=True) # 지방
    price = models.IntegerField(default=0)
    sold_count = models.IntegerField(default=0)  # 상품 팔린 갯수
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])   # 구입할 상품 갯수
    hit = models.PositiveIntegerField(default=0) # 조회수는 음수일 수 없음
    brand = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    ddib_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="ddib_users") 
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='img/')

# User - Cart (1:1)
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
    ])   # 구입할 상품 갯수
    
# User - Ddib (1:1)
class Ddib(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class DdibItem(models.Model):
    ddib = models.ForeignKey(Ddib, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# 상품 문의
class Inquiry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def status(self):
        return self._meta.model.status

# 문의 답변
class Reply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    inquiry = models.OneToOneField(Inquiry, on_delete=models.CASCADE)
    # title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # product_name = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField('제목', max_length=50)
    content = models.TextField('후기작성')
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기 이미지
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    review_img = models.ImageField('사진등록', upload_to='img/', blank=True, null=True) # 리뷰 이미지 생략 가능하도록

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile, OrderItem, User
from products.models import Product, Image
from django.forms import ModelForm, ClearableFileInput


class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "address")
            
        def clean_username(self):
            username = self.cleaned_data['username']
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('아이디가 이미 사용중입니다')
            return username


class CustomUserChangeForm(UserChangeForm):
    password = None
    
    class Meta():
        model = get_user_model()
        fields = (
            "username",
            "image",
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile()
        fields = ["image",]
        labels = {
            'image': '프로필 사진'
        }


# admin이 사용자의 구매상품 정보를 등록할 때의 form
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'price', 'brand', 'category']


# ClearableFileInput을 사용해서 여러 장의 이미지를 받음
class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['image']
        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True})
        }
        

class ProductBuyForm(ModelForm):
    class Meta:
        model = Product
        fields = ['quantity']
        labels = {'quantity': '수량'}

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, ProfileForm
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from products.models import Cart, Ddib
from .models import OrderItem, WatchItem, Product, User
from django.contrib import messages
from .forms import ProductBuyForm
from products.models import *
from products.forms import *
from django.http import JsonResponse
import json
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.
def signup(request):
    if request.method == "POST":
        forms = SignupForm(request.POST, request.FILES)
        if forms.is_valid():
            user = forms.save()      
            Cart.objects.create(user=user)
            Ddib.objects.create(user=user)
            # UserDdib.objects.create(user=user)
            return redirect("articles:index")
    else:
        forms = SignupForm()
    context = {
        "forms": forms,
    }
    return render(request, "accounts/signup.html", context)

def isValidId(request):
    data = json.loads(request.body)
    username = data.get("username")
    print(data)

    if User.objects.filter(Q(username = data['username'])).exists():
        flag = 1
    else:
        flag = 0

    context = {
        "flag": flag,
        }
    return JsonResponse(context)

def index(request):
    members = get_user_model().objects.all()
    return render(request, "accounts/index.html")


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
        messages.warning(request, '아이디, 비밀번호를 확인해주세요', extra_tags='')
    else:
        form = AuthenticationForm()
    context = {"forms": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def profile_update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        password_form = PasswordChangeForm(request.user, request.POST)
        address = request.POST.get('address')

        if form.is_valid():
            form.save()

        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, password_form.user)

        if address:
            user=request.user
            user.address = address
            user.save()

        return redirect("accounts:profile", request.user.pk) 

    else:
        form = CustomUserChangeForm(instance=request.user)
        password_form = PasswordChangeForm(request.user)

    context = {
        "form": form,
        "password_form": password_form
    }

    return render(request, "accounts/profile_update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        forms = PasswordChangeForm(request.user, request.POST)
        if forms.is_valid():
            forms.save()
            update_session_auth_hash(request, forms.user)  # 로그인 유지
            return redirect("accounts:profile")
    else:
        forms = PasswordChangeForm(request.user)
    context = {
        "forms": forms,
    }
    return render(request, "accounts/change_password.html", context)
    
@login_required
def profile(request, user_pk):
    products = Product.objects.order_by('-pk')
    user = get_object_or_404(get_user_model(), pk=user_pk)
    ddib = Ddib.objects.get(user=user) # 요청한 사용자의 찜(가방)을 가져와라.
    ddib_items = ddib.ddibitem_set.all() # 찜한 목록(가방 안에 있는 물건들)을 가져와라.
    
    # 중복되지 않은 상품 id 리스트
    order_product_ids = OrderItem.objects.filter(user=user).values_list('product', flat=True).distinct()
    order_items = []
    for id in order_product_ids:
        order_items.append(Product.objects.get(pk=id))

    watch_items = WatchItem.objects.filter(user=user)
    inquiries = user.inquiry_set.order_by('-pk')


    product_buy_form = ProductBuyForm() 
    cart = Cart.objects.get(user=user)
    cart_items = cart.cartitem_set.all()

    # 문의 페이지네이션
    inquiry_page = request.GET.get('inquiry_page', '1')
    inquiry_paginator = Paginator(inquiries, 5)
    inquiry_page_obj = inquiry_paginator.get_page(inquiry_page)

    # 총 구매 금액, 포인트 및 등급
    total_payment = sum(OrderItem.objects.filter(user=user).values_list('price', flat=True))
    total_point = total_payment // 10
    
    if total_point >= 50000:
        user.rating = 'GOLD'
        user.save()
    elif total_point >= 30000:
        user.rating = 'SILVER'
        user.save()
    
    context = {
        "person": user,
        "ddib_items": ddib_items,
        'product_buy_form': product_buy_form,
        'order_items': order_items,
        'watch_items': watch_items,
        'cart_items': cart_items,
        'inquiries': inquiry_page_obj,
        'products': products,
        'total_payment': total_payment,
        'total_point': total_point,
    }

    return render(request, "accounts/profile.html", context)

# 찜한 상품 삭제
def ddib_delete(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    ddib = Ddib.objects.get(user=request.user) # user와 ddib 1:1
    ddib_items = ddib.ddibitem_set.all()

    for item in ddib_items:
        if product == item.product:
            item.delete()
            break
    return redirect('accounts:profile', request.user.pk)


@login_required
def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        return redirect("accounts:profile", user_pk)
    else:
        return HttpResponseForbidden()


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:login")


# 로그인한 유저의 장바구니 페이지
@login_required
def cart(request):
    cart = Cart.objects.get(user=request.user)

    cart_items = cart.cartitem_set.all()
    
    # 장바구니 기본이 checked일 때
    # total_price = 0
    # for item in cart_items:
    #     total_price += item.product.price * item.quantity

    context = {
        'cart_items': cart_items,
        # 'total_price': total_price,
    }

    return render(request, 'accounts/cart.html', context)


# 장바구니에서 삭제
@login_required
def cart_update(request):
    cart = Cart.objects.get(user=request.user)
    selected_items = request.POST.getlist('selected_items') # 선택된 아이템들의 product_pk 리스트
    
    # print(request.POST)
    deleted_item_pk_list = []

    if 'select_delete' in request.POST.get('kindOfSubmit'):
        for i in range(len(selected_items)):
            # 선택된 장바구니 아이템의 pk로 아이템 인스턴스 객체를 가져옴.
            cart_item = cart.cartitem_set.get(pk=selected_items[i])
            cart_item.delete()
            deleted_item_pk_list.append(selected_items[i])
    
    elif 'delete' in request.POST.get('kindOfSubmit'):
        product_pk = request.POST.get('productPk')
        cart_item = cart.cartitem_set.get(pk=product_pk)
        cart_item.delete()
        deleted_item_pk_list.append(product_pk)

    data = {
        'deletedItemList': deleted_item_pk_list,
    }

    # return redirect('accounts:cart')
    return JsonResponse(data, safe=False)

def tocart(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    cart = Cart.objects.get(user=request.user)

    cart_items = cart.cartitem_set.all()

    # if request.method == 'POST':
    #     cartitem = CartItem()
    #     cartitem.quantity = request.POST['checkquantity']
       
    #     cartitem.cart = Cart.objects.get(pk=request.user.pk)
    #     cartitem.product = product
        
    #     cartitem.save()

    if request.method == 'POST':
        for item in cart_items:
            if item.product.pk == product_pk:
                item.quantity += int(request.POST['checkquantity'])
                item.save()
                break
        else:
            CartItem.objects.create(cart=cart, product=product, quantity=int(request.POST['checkquantity']))
            
    return redirect('accounts:cart')


# 장바구니 결제
def payment(request):
    cart = Cart.objects.get(user=request.user)

    imp_uid = request.POST.get('imp_uid')
    merchant_uid = request.POST.get('merchant_uid')
    selected_items = request.POST.getlist('selected_items') # 선택된 아이템들의 product_pk 리스트
    quantities = request.POST.getlist('quantities') # 선택된 아이템들의 quantity 리스트
    
    for i in range(len(selected_items)):
        # 1. 선택된 장바구니 아이템의 pk로 아이템 인스턴스 객체를 가져옴.
        cart_item = cart.cartitem_set.get(pk=selected_items[i])
        # 2. 장바구니 페이지에서 수정된 수량으로 변경
        quantity = int(quantities[i])
        
        # 위의 정보를 바탕으로 주문서 작성
        OrderItem.objects.create(product=cart_item.product, quantity=quantity, user=request.user, imp_uid=imp_uid, merchant_uid=merchant_uid, price=cart_item.product.price * quantity)
        cart_item.product.sold_count += 1
        cart_item.product.save()
        cart_item.delete()

    return redirect('accounts:cart')

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

  <div class="d-flex justify-content-center">
    <div class="card text-center mb-5 border-0" style="width: 330px; margin: 50px auto 50px;">
      <div class="card-body">
        <div class="card-text">
          {% if user.is_authenticated %}
          <a class='btn w-100 mb-5 py-2' href="{% url 'accounts:logout' %}" style="background-color: #5e0080; border-color:#5e0080; color: white; font-weight: 500; border-radius: 3px"; >치킨컬리에서 로그아웃</a>
          {% else %}
            <p class="mt-5">회원이신가요?</p>
            <a class="btn btn-primary w-100" style=" background-color: #5e0080; border-color:#5e0080; color: white; font-weight: 500; border-radius: 3px"  href="{% url 'accounts:login' %}">로그인</a>
            <p class="mt-5">아직 회원이 아니신가요?</p>
            <a class="btn btn-primary w-100 mb-5" style="border:1px solid #5e0080;background-color: white; color: #5e0080; font-weight: 500; border-radius: 3px" href="{% url 'accounts:signup' %}">회원가입</a>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>  

  <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
  <script>
    const swiper = new Swiper('#test-slide', {
      // Optional parameters
      direction: 'horizontal',
      slidesPerView: 4,
      spaceBetween: 15,
      loop: false,

      // If we need pagination
      pagination: {
        el: '.swiper-pagination'
      },

      // Navigation arrows
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      },

      // And if we need scrollbar
      // scrollbar: {
      //   el: '.swiper-scrollbar',
      // },
    });
  </script>

{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}

  <!-- profile update -->
  <!-- 비밀번호 변경 -->

<section class="container" style="width: 640px;height: 1315px; margin-top: 50px;">
  <form class='mx-5' action="{% url 'accounts:profile_update' %}" method="POST" style="border-top: 0px solid rgb(51, 51, 51); font-size:14px;" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="mb-5 text-center" style='color:#5e0080;'>개인정보 수정</h1>
    <fieldset class="form-group">
      <legend class="border-bottom mb-4"></legend>
      <div>
        <h6>아이디</h6>
        <p class="form-control" style="background-color: rgb(221, 225, 227); color:#212529">{{ user.username }}</p>
        
        {% bootstrap_form password_form %}

        <div class="">
          <div style="display: none;">
            <p type="text" id="sample6_postcode" placeholder="우편번호"></p>
            <p type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br></p>
            <p type="text" id="sample6_address" placeholder="주소"><br></p>
            <p type="text" id="sample6_detailAddress" placeholder="상세주소"></p>
            <p type="text" id="sample6_extraAddress" placeholder="참고항목"></p>
          </div>
          <h6 class="my-3 fw-bold" style="color: rgb(51, 51, 51); font-size:14px;">배송받을 주소</h6>
          <div class="my-3 d-flex">
            <input type="text" name="address" class="signup-input form-control"
              placeholder="주소를 입력해주세요" id="sample6_address2">
            <input class="btn" type="button"
              style="width: 120px; height: 33.5px; border: 1px solid #5e0080; color: #5e0080; margin-left: 8px; font-weight: 500;"
              value="주소검색" onclick="sample6_execDaumPostcode()">
          </div>
      </div>
          {% bootstrap_form form %}
          <input type="submit" class="btn" style='background-color: #5e0080; border-color: #5e0080; color:white' value="수정">
          {% comment %} <a href="{% url 'accounts:change_password' %}" class="btn" style='border: 1px solid #5e0080; color: #5e0080; font-weight: 500'>비밀번호 수정</a> {% endcomment %}
          <a href="" class="btn" style='border: 1px solid #5e0080; color: #5e0080; font-weight: 500'>돌아가기</a>
          <a href="{% url 'accounts:delete' %}" class="btn float-end" style='border: 1px solid #5e0080; color: #5e0080; font-weight: 500'>회원탈퇴</a>
        </fieldset>
      </form>

  <!-- code for use <button type="button" class="btn btn-outline-dark" href="{% url 'accounts:profile' request.user.pk %}">돌아가기</button> </form> 배송지 <form class="mx-3" action="{% url 'accounts:profile_update' %}" style="border-top: 0px solid rgb(51, 51, 51); font-size:14px;" method="POST"> {% csrf_token %} <div class="d-flex align-items-center"> <h6 class="my-3">배송지</h6> <div class="my-3"> <input type="text" name="" class="signup-input form-control" placeholder="주소를 입력해주세요"> </div> <div> <input class="btn" value="주소검색"> </div> </div> </form>-->
  <!-- buttons copied <form action="" method="POST" enctype="multipart/form-data"> <div class="container"> <div class="row"> <div class="col-4 p-3"> <div class="d-flex align-items-center"> {% if request.user.image %} <img src="{{ request.user.image.url }}" alt="" style="width: 150px; height: 150px; border-radius: 50%"> {% else %} <img src="" alt=""> {% endif %}-->
  <!-- <p class="fs-3 my-2 ms-5">{{ user.username }}</p> -->
  <!-- </div> </div> </div> <form action="{% url "accounts:profile_update" %}" method="POST"> {% csrf_token %} {% bootstrap_form form %} <input type="submit" class="btn btn-outline-dark" value="수정"> <a href="{% url 'accounts:change_password' %}" class="btn btn-secondary">비밀번호 수정</a> <a href="{% url 'accounts:delete' %}" class="btn btn-secondary">회원탈퇴</a> <a href="" class="btn btn-secondary">돌아가기</a> </form>-->
</section>

{% endblock content %}

{% block script %}
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>

<script>
  const oldPW = document.querySelector('#id_old_password')
  const newPW1 = document.querySelector('#id_new_password1')
  const newPW2 = document.querySelector('#id_new_password2')

  // console.log(oldPW)
  // console.log(newPW1)
  // console.log(newPW2)
  oldPW.removeAttribute('required')
  newPW1.removeAttribute('required')
  newPW2.removeAttribute('required')

  function sample6_execDaumPostcode() {
    new daum.Postcode({
      oncomplete: function (data) {
        // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
        
        // 각 주소의 노출 규칙에 따라 주소를 조합한다.
        // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
        var addr = ''; // 주소 변수
        var extraAddr = ''; // 참고항목 변수

        //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
        if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
          addr = data.roadAddress;
        } else { // 사용자가 지번 주소를 선택했을 경우(J)
          addr = data.jibunAddress;
        } 

        // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
        if (data.userSelectedType === 'R') {
          // 법정동명이 있을 경우 추가한다. (법정리는 제외)
          // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
          if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {
            extraAddr += data.bname;
          }
          // 건물명이 있고, 공동주택일 경우 추가한다.
          if (data.buildingName !== '' && data.apartment === 'Y') {
            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
          }
          // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
          if (extraAddr !== '') {
            extraAddr = ' (' + extraAddr + ')';
          }
          // 조합된 참고항목을 해당 필드에 넣는다.
          document.getElementById("sample6_extraAddress").innerText = extraAddr;

        } else {
          document.getElementById("sample6_extraAddress").innerText = '';
        }

        // 우편번호와 주소 정보를 해당 필드에 넣는다.
        document.getElementById('sample6_postcode').value = data.zonecode;
        document.getElementById("sample6_address").value = addr;
        document.getElementById("sample6_address2").value = addr;
        // 커서를 상세주소 필드로 이동한다.
        document.getElementById("sample6_detailAddress").focus();
      }
    }).open();
  }

</script>
{% endblock script %}