PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.profile, name="profile"),
    path("profile_update/", views.profile_update, name="profile_update"),
    path("delete/", views.delete, name="delete"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("change_password/", views.change_password, name="change_password"),
    path('cart/', views.cart, name='cart'), # 장바구니 페이지
    path('cart/update/', views.cart_update, name='cart_update'), # 장바구니 구매 및 삭제
    path('cart/payment/', views.payment, name='payment'),
    path('<int:product_pk>/ddib_delete/', views.ddib_delete, name='ddib_delete'), # 프로필에서 찜한 상품(product_pk) 삭제
    path('<int:product_pk>/tocart/', views.tocart, name='tocart'), # 찜한 상품 모달에서 수량 선택 후 장바구니로 담기
    path('isValidId/', views.isValidId, name='isValidId'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("comment/<int:pk>/", views.c_create, name="c_create"),
    path("comment/<int:c_pk>/delete/<int:a_pk>", views.c_delete, name="c_delete"),
    path("like/<int:pk>/", views.like, name="like"),
    path("c_like/<int:c_pk>/", views.c_like, name="c_like"),
    path("rec_like/<int:c_pk>/<int:a_pk>", views.rec_like, name="rec_like"),
    path("rec_create/<int:c_pk>/<int:a_pk>", views.rec_create, name="rec_create"),
    path("rec_detail_create/<int:c_pk>/<int:a_pk>", views.rec_detail_create, name="rec_detail_create"),
    path("rec_detail/<int:c_pk>/<int:a_pk>", views.rec_detail, name="rec_detail"),
    path("search/", views.search, name="search"),
    path("recomment/<int:c_pk>/delete/<int:a_pk>", views.recomment_delete, name="recomment_delete"),    
    path("rec_delete/<int:rec_pk>/<int:c_pk>/<int:a_pk>", views.rec_delete, name="rec_delete"),    
] 

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/ddib/', views.ddib, name='ddib'),
    path('<int:product_pk>/cart/', views.cart, name='cart'),
    path('<int:product_pk>/review_create/', views.review_create, name='review_create'),
    path('<int:product_pk>/<int:review_pk>/review_update/', views.review_update, name='review_update'),
    path('<int:product_pk>/inquiry/', views.create_inquiry, name='create_inquiry'),   # 문의 등록
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/update/', views.update_inquiry, name='update_inquiry'),   # 문의 수정
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/delete/', views.delete_inquiry, name='delete_inquiry'),   # 문의 삭제
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/reply/', views.create_reply, name='create_reply'),   # 답변 등록
    path('<int:product_pk>/payment/', views.payment, name='payment'),
]

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill
from django.conf import settings


# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="img/",
        blank=True,
        processors=[Thumbnail(1920, 1080)],  
        format="JPEG", 
        options={"quality": 100},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles")


class Comment(models.Model):
    content = models.CharField(max_length=300)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_comments")

class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

products/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=36)
    content = models.CharField(max_length=27)   # 상품 짧은 소개
    carbohydrate = models.FloatField(blank=True)    # 탄수화물
    protein = models.FloatField(blank=True) # 단백질
    fat = models.FloatField(blank=True) # 지방
    price = models.IntegerField(default=0)
    sold_count = models.IntegerField(default=0)  # 상품 팔린 갯수
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])   # 구입할 상품 갯수
    hit = models.PositiveIntegerField(default=0) # 조회수는 음수일 수 없음
    brand = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    ddib_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="ddib_users") 
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='img/')

# User - Cart (1:1)
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
    ])   # 구입할 상품 갯수
    
# User - Ddib (1:1)
class Ddib(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class DdibItem(models.Model):
    ddib = models.ForeignKey(Ddib, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# 상품 문의
class Inquiry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def status(self):
        return self._meta.model.status

# 문의 답변
class Reply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    inquiry = models.OneToOneField(Inquiry, on_delete=models.CASCADE)
    # title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # product_name = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField('제목', max_length=50)
    content = models.TextField('후기작성')
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기 이미지
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    review_img = models.ImageField('사진등록', upload_to='img/', blank=True, null=True) # 리뷰 이미지 생략 가능하도록

articles/forms.py
from django import forms
from .models import Article, ReComment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]


class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        
        fields = ["content",]
        labels = {
            'content': '답글'
        }

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, ReCommentForm
from .models import Article, Comment, ReComment
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required  
from django.http import JsonResponse
from products.models import Product
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.


def index(request):

    articles = Article.objects.order_by('-pk')
    comments = Comment.objects.order_by('-pk')

    page = request.GET.get('page', '1')
    paginator = Paginator(articles, 9)
    paginated_articles = paginator.get_page(page)
    max_index = len(paginator.page_range)


    context = {
        "articles": articles,
        "paginated_articles": paginated_articles,
        "max_index": max_index,
        "comments": comments,
    }

    return render(request, 'articles/index.html', context)

@login_required
def create(request):

    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
    context = {
        "article_form": article_form,
    }
    return render(request, "articles/create.html", context)

@login_required
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comments = Comment.objects.filter(article=article).order_by('-pk')
    recomment_form = ReCommentForm()
    recomments = ReComment.objects.all().order_by('-pk')

    page = request.GET.get('page', '1')
    paginator = Paginator(comments, 5)
    paginated_comments = paginator.get_page(page)
    max_index = len(paginator.page_range)

    context = {
        'article': article,
        'comments': comments,
        'recomment_form': recomment_form,
        'paginated_comments': paginated_comments,
        'max_index': max_index,
        'recomments': recomments,
    }

    return render(request, "articles/detail.html", context)

def rec_detail(request, c_pk, a_pk):

    article = Article.objects.get(pk=a_pk)
    comment = Comment.objects.get(pk=c_pk)
    recomments = ReComment.objects.filter(comment=comment).order_by('-pk')
    recomment_form = ReCommentForm()

    # 대댓글 페이지네이션
    recomment_page = request.GET.get('recomment_page', '1')
    recomment_paginator = Paginator(recomments, 5)
    recomment_page_obj = recomment_paginator.get_page(recomment_page)

    # page = request.GET.get('page', '1')
    # paginator = Paginator(recomments, 5)
    # paginated_recomments = paginator.get_page(page)
    # max_index = len(paginator.page_range)

    context = {
        'comment': comment,
        'recomments': recomments,
        'recomments': recomment_page_obj,
        # 'paginated_recomments': paginated_recomments,
        'recomment_form': recomment_form,
        # 'max_index': max_index,
        'article': article,
    }

    return render(request, 'articles/recomment.html', context)

@login_required
def delete(request, pk):

    article = Article.objects.get(pk=pk)

    if request.user == article.user:
        article.delete()
    return redirect("articles:index")

@login_required
def update(request, pk):

    article = Article.objects.get(pk=pk)

    if request.user == article.user:
        if request.method == "POST":
            article_form = ArticleForm(request.POST, request.FILES, instance=article)
            if article_form.is_valid():
                article_form.save()
                return redirect("articles:index")
        else:
            article_form = ArticleForm(instance=article)
        context = {
            "article_form": article_form,
            "article": article,
        }
        return render(request, "articles/update.html", context)
    return redirect("articles:index")


@login_required
def c_create(request,pk):

    comment = request.POST.get("comment")
    article = Article.objects.get(pk=pk)

    Comment.objects.create(content=comment, article=article, user=request.user)
    
    # 댓글 비동기를 위한 코드
    # context = {
    #     'content': comment,
    #     'userName': request.user.username,
    # }

    return redirect('articles:detail', pk)

@login_required
def rec_create(request, c_pk, a_pk):

    if request.method == 'POST':
        comment = Comment.objects.get(pk=c_pk)
        recomment_form = ReCommentForm(request.POST)
        if recomment_form.is_valid():
            recomment = recomment_form.save(commit=False)
            recomment.comment = comment
            recomment.user = request.user
            recomment.save()
        return redirect('articles:detail', a_pk)

@login_required
def rec_detail_create(request, c_pk, a_pk):

    if request.method == 'POST':
        comment = Comment.objects.get(pk=c_pk)
        recomment_form = ReCommentForm(request.POST)
        if recomment_form.is_valid():
            recomment = recomment_form.save(commit=False)
            recomment.comment = comment
            recomment.user = request.user
            recomment.save()
        return redirect('articles:rec_detail', c_pk, a_pk)
    


@login_required
def c_delete(request, c_pk, a_pk):

    comment = Comment.objects.get(pk=c_pk)
    comment.delete()

    return redirect("articles:detail", a_pk)

# 대댓글 삭제
@login_required
def recomment_delete(request, c_pk, a_pk):

    recomment = ReComment.objects.get(pk=c_pk)
    recomment.delete()

    return redirect("articles:rec_detail", c_pk, a_pk)


@login_required
def rec_delete(request, rec_pk, c_pk, a_pk):

    recomment = ReComment.objects.get(pk=rec_pk)
    recomment.delete()

    return redirect('articles:rec_detail', c_pk, a_pk)


@login_required
def like(request, pk):

    if request.user.is_authenticated:
        article = Article.objects.get(pk=pk)

        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            is_liked = False
        else:
            article.like_users.add(request.user)
            is_liked = True

        like_count = article.like_users.count()
        
        context = {
            'is_liked': is_liked,
            'likeCount': like_count,

        }
        return JsonResponse(context)
    return redirect('accounts:login')

@login_required
def c_like(request, c_pk):

    if request.user.is_authenticated:

        comment = Comment.objects.get(pk=c_pk)

        if request.user in comment.like_users.all():
            comment.like_users.remove(request.user)
            comment_is_liked = False
        else:
            comment.like_users.add(request.user)
            comment_is_liked = True

        like_count = comment.like_users.count()

        context = {
            'comment_is_liked': comment_is_liked,
            'like_count': like_count,
        }

        return JsonResponse(context)
    return redirect('accounts:login')


@login_required
def rec_like(request, c_pk, a_pk):

    if request.user.is_authenticated:

        comment = Comment.objects.get(pk=c_pk)

        if request.user in comment.like_users.all():
            comment.like_users.remove(request.user)
        else:
            comment.like_users.add(request.user)

        return redirect('articles:rec_detail', c_pk, a_pk)
    return redirect('accounts:login')

def search(request):
    keyword = request.GET.get("keyword", "")  # 검색어

    if keyword:
        products = Product.objects.filter(
            Q(product_name__icontains=keyword) | Q(brand__icontains=keyword)
        ).distinct()
        articles = Article.objects.filter(
            Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ).distinct()
        context = {
            "products": products,
            "articles": articles,
            "keyword": keyword,
        }
        return render(request, "articles/search.html", context)

articles/templates/articles/recomment.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<body style="background-color: rgb(245, 245, 245)">
  <div class='comment-grid container ' style="width: 1280px; padding: 40px 0;">
    <div class='my-5 d-grid' style="grid-template-columns: 40px auto;">
    {% comment %} 뒤로 가기 버튼 {% endcomment %}
      <div>
        <a class="non_a" style="font-size: 1.4rem;" href="{% url 'articles:detail' article.pk %}">
            <ion-icon name="arrow-back-outline" style="color: #3d3d3d; margin-bottom: 14px"></ion-icon>
          </a>
      </div>

      <div class="rounded-3" style="background-color: white; border: 1px solid rgb(222, 222, 222);">
        <div class='mx-2 mt-2' style='margin: -2px;'>
          <div class='d-flex flex-column'>
            <!-- 댓글 작성자, 시간 -->
            <div class="flex-grow-1 px-3 py-2" >
              <div class="d-flex align-items-center justify-content-between">
                <div>
                  <span>
                    {% if comment.user.image %}
                      <img src='{{ comment.user.image.url }}' style="border-radius: 50%; width:40px; height:40px">
                    {% else %}
                      <img src="{% static 'images/android-icon-72x72.png' %}" style="border-radius: 50%; width:40px; height:40px">
                    {% endif %}
                  </span>
                  <span style="font-size: 1rem"><a class="non_a" href="{% url 'accounts:profile' comment.user.pk %}"
                      style="font-weight: 600; color: rgb(61, 61, 61);">{{ comment.user }}</a></span>
                  <span class="mx-1" style="color: rgb(189, 189, 189);">•</span>
                  <span style="color: rgb(113, 113, 113); font-weight: 400; font-size: 14px;">
                    {{ comment.created_at|date:'Y년 m월 d일' }}</span>
                </div>
                <!-- 댓글 삭제 --> 
                {% if request.user == comment.user %}
                <span>
                  <a href="{% url 'articles:c_delete' comment.pk article.pk %}">
                    <span style="color: #e83c4b; display: inline-block; transform: translateY(3px); font-size: 1rem;">
                      <i class="bi bi-x"></i>
                    </span>
                  </a>
                </span>
                {% endif %}
              </div>
              <!-- 댓글 내용 및 좋아요 버튼, 좋아요 갯수 -->
              <div style="margin: 12px 0 16px;">
                <p class="text-break m-0" style="font-size: 18px; line-height: 27px">{{ comment.content }}
                </p>
              </div>
              <div class="d-flex align-items-center">
                <form class="comment-like-forms" data-comment-id="{{ comment.pk }}">
                  {% if request.user in comment.like_users.all %}
                  <button type="submit" class="d-flex text-center" style="border: 0px; background: transparent;"
                    id='comment-like-btn-{{ comment.pk }}'>
                    <div class="fs-6" style="color: #7f1ba4">
                      <span>
                        <i id='thumbs-up-{{ comment.pk }}' class="bi bi-hand-thumbs-up-fill"></i>
                      </span>
                      <span class="me-3" id='comment-like-count-{{ comment.pk }}' style="font-size: 14px;">
                        {{ comment.like_users.count }}
                      </span>
                    </div>
                  </button>
                  {% else %}
                  <button type="submit" class="d-flex text-center" style="border: 0px; background: transparent;"
                    id='comment-like-btn-{{ comment.pk }}'>
                    <div class="fs-6" style="color: #7f1ba4">
                      <span>
                        <i id='thumbs-up-{{ comment.pk }}' class="bi bi-hand-thumbs-up"></i>
                      </span>
                      <span class="me-3" id='comment-like-count-{{ comment.pk }}' style="font-size: 14px;">
                        {{ comment.like_users.count }}
                      </span>
                    </div>
                  </button>
                  {% endif %}
                </form>
              </div> 

            </div>
            <hr class='border-3 opacity-100 '>
            <!-- 대댓글 -->
            <div class="card card-body w-100" style="border: rgb(231, 231, 231);">
              <div class='p-1 '>
                <!-- 대댓글 목록 -->
                <div style="display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 12; overflow: hidden;">
                  {% for recomment in recomments %}

                  {% if recomment.comment.pk == comment.pk %}
                  
                  <div class='my-5 d-grid' >
                    
                    <div class="d-flex align-items-center justify-content-between">
                      <div>
                        <span style="">
                          {% if recomment.user.image %}
                          <img src='{{ recomment.user.image.url }}' style="border-radius: 50%; width:32px; height:32px">
                          {% else %}
                          <img src="{% static 'images/android-icon-72x72.png' %}"
                            style="border-radius: 50%; width:32px; height:32px">
                          {% endif %}
                        </span> 
                        <span><a class="non_a" href="{% url 'accounts:profile' recomment.user.pk %}"
                            style="font-weight: 600; color: rgb(61, 61, 61);">{{ recomment.user }}</a></span>
                        <span class="mx-1" style="color: rgb(189, 189, 189);">•</span>
                        <span style="color: rgb(113, 113, 113); font-weight: 400; font-size: 14px">
                          {{ recomment.created_at|date:'Y년 m월 d일 H시 t분 s초' }}</span>

                        {% if request.user == recomment.user %}
                        <span>
                          <a href="{% url 'articles:rec_delete' recomment.pk comment.pk article.pk %}">
                            <span style="color: #e83c4b; display: inline-block; transform: translateY(3px);">
                              <i class="bi bi-x"></i>
                            </span>
                          </a>
                        </span>
                        {% endif %}
                        <div class="text-break" style="margin-top: 12px;">
                          {{ recomment.content }}
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endif %}

                  {% endfor %}
                </div>  
                <!-- 대댓글 입력창 -->
                <div class='mb-2'> 
                  <form action="{% url 'articles:rec_detail_create' comment.pk article.pk %}" method='POST' enctype='multipart/form-data' maxlength="200">
                    {% csrf_token %}
                    {% bootstrap_form recomment_form %}
                    <button type="submit" class="btn mb-2" style='background-color:#5e0080; color:white;'>OK</button>
                  </form>
                </div>
                <div class='page d-flex justify-content-center' style='padding-top:20px'>
                  <!-- 댓글 페이지네이션 -->
                  <ul class="pagination justify-content-center">
                    <!-- 이전 페이지 -->
                    {% if recomments.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?recomment_page={{ recomments.previous_page_number }}" aria-label="Previous">
                        <i class="bi bi-chevron-double-left"></i>
                      </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                        <i class="bi bi-chevron-double-left"></i>
                      </a>
                    </li>
                    {% endif %}

                    <!-- 페이지 리스트 -->
                    {% for page_number in recomments.paginator.page_range %}
                    {% if page_number == recomments.number %}
                    <li class="page-item active" aria-current="page">
                      <a class="page-link" style='background-color:#5e0080; border-color:#dee2e6;'
                        href="?recomment={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                      <a class="page-link" style='background-color:#5e0080; border-color:#dee2e6;'
                        href="?recomment_page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음페이지 -->
                    {% if reviews.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?recomment_page={{ recomments.next_page_number }}">
                        <i class="bi bi-chevron-double-right"></i>
                      </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                        <i class="bi bi-chevron-double-right"></i>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div> 
        </div>       
      </div>
    </div>
  </div>
</body>

<script>
  // 댓글 좋아요 비동기
  const commentforms = document.querySelectorAll('.comment-like-forms')
  const commentcsrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  commentforms.forEach((form) => {
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const commentId = event.target.dataset.commentId

      axios({
        method: 'post',
        url: `/articles/c_like/${event.target.dataset.commentId}/`,
        headers: { 'X-CSRFToken': commentcsrftoken },
      })
        .then((response) => {
          const commentlikeBtn = document.querySelector(`#comment-like-btn-${commentId}`)
          const likeCount = document.querySelector(`#comment-like-count-${commentId}`)
          const commentisLiked = response.data.comment_is_liked
          const thumbsUp = document.querySelector(`#thumbs-up-${commentId}`)
          console.log(likeCount)

          if (commentisLiked === true) {
            thumbsUp.classList.remove('bi-hand-thumbs-up')
            thumbsUp.classList.add('bi-hand-thumbs-up-fill')
            // heart.classList.remove('bi-heart')
            // likeBtn.classList.remove('btn-outline-danger')
            // likeBtn.classList.add('btn-danger')
            likeCount.innerText = response.data.like_count
          } else {
            thumbsUp.classList.remove('bi-hand-thumbs-up-fill')
            thumbsUp.classList.add('bi-hand-thumbs-up')
            // heart.classList.add('bi-heart')
            // likeBtn.classList.remove('btn-danger')
            // likeBtn.classList.add('btn-outline-danger')
            likeCount.innerText = response.data.like_count
          }

        })
    })
  })
 

</script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>


{% endblock content %}