PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/ddib/', views.ddib, name='ddib'),
    path('<int:product_pk>/cart/', views.cart, name='cart'),
    path('<int:product_pk>/review_create/', views.review_create, name='review_create'),
    path('<int:product_pk>/<int:review_pk>/review_update/', views.review_update, name='review_update'),
    path('<int:product_pk>/inquiry/', views.create_inquiry, name='create_inquiry'),   # 문의 등록
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/update/', views.update_inquiry, name='update_inquiry'),   # 문의 수정
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/delete/', views.delete_inquiry, name='delete_inquiry'),   # 문의 삭제
    path('<int:product_pk>/inquiry/<int:inquiry_pk>/reply/', views.create_reply, name='create_reply'),   # 답변 등록
    path('<int:product_pk>/payment/', views.payment, name='payment'),
]

products/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=36)
    content = models.CharField(max_length=27)   # 상품 짧은 소개
    carbohydrate = models.FloatField(blank=True)    # 탄수화물
    protein = models.FloatField(blank=True) # 단백질
    fat = models.FloatField(blank=True) # 지방
    price = models.IntegerField(default=0)
    sold_count = models.IntegerField(default=0)  # 상품 팔린 갯수
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])   # 구입할 상품 갯수
    hit = models.PositiveIntegerField(default=0) # 조회수는 음수일 수 없음
    brand = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    ddib_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="ddib_users") 
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='img/')

# User - Cart (1:1)
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
    ])   # 구입할 상품 갯수
    
# User - Ddib (1:1)
class Ddib(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class DdibItem(models.Model):
    ddib = models.ForeignKey(Ddib, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# 상품 문의
class Inquiry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def status(self):
        return self._meta.model.status

# 문의 답변
class Reply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    inquiry = models.OneToOneField(Inquiry, on_delete=models.CASCADE)
    # title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # product_name = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField('제목', max_length=50)
    content = models.TextField('후기작성')
    created_at = models.DateTimeField(auto_now_add=True)

# 상품 후기 이미지
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    review_img = models.ImageField('사진등록', upload_to='img/', blank=True, null=True) # 리뷰 이미지 생략 가능하도록

products/forms.py
from django.forms import ModelForm, ClearableFileInput
from .models import *


# admin이 판매상품 정보를 등록할 때의 form
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'content', 'carbohydrate', 'protein', 'fat', 'price', 'brand', 'category']

# 일반 user가 구매할 때 form (구매 수량만)
class ProductBuyForm(ModelForm):
    class Meta:
        model = Product
        fields = ['quantity']
        labels = {'quantity': '수량'}
        
# ClearableFileInput으로 여러 장의 image를 입력 받을 수 있음
class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['image']
        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True})
        }

# 후기 작성 폼
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

# 후기에 등록하는 이미지
class ReviewImageForm(ModelForm):
    class Meta:
        model = ReviewImage
        fields = ['review_img']
        widgets = {
            'review_img': ClearableFileInput(attrs={'multiple': True})
        }

# 상품 문의 form
class InquiryForm(ModelForm):
    class Meta:
        model = Inquiry
        fields = ['title', 'content']
        labels = {
            'title': '제목',
            'content': '내용',
        }

# 상품 문의에 대한 답변 form
class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {
            'content': '내용',
        }

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from accounts.models import OrderItem
from .forms import *
from django.http import JsonResponse
from django.core.paginator import Paginator

from dotenv import load_dotenv
import os

# Create your views here.
def index(request):
    load_dotenv()  # .env 파일에서 환경 변수를 불러옵니다.
    ACCESS_TOKEN = os.getenv("API_TOKEN")
    products = Product.objects.order_by('-pk')
    products_name = Product.objects.order_by('product_name')
    categories = Product.objects.values('category').distinct()
    review = Review.objects.order_by('-pk')
    hits = Product.objects.order_by('-hit')
    sold = Product.objects.order_by('-sold_count')
    # print(categories)

    context = {
        'products': products,
        'review':review,
        'hits': hits,
        'sold': sold,
        'ACCESS_TOKEN': ACCESS_TOKEN,
        'categories': categories,
        'products_name': products_name,
        # 'image_cnt': products.image_set.count(), # index 페이지에서 carousel로 보여줄 때 사용
    }

    return render(request, 'products/index.html', context)


# admin의 판매 상품 등록
@login_required
def create(request):
    # 요청한 user의 is_superuser가 1이면(admin이면)
    if request.user.is_superuser == 1: 
        if request.method == 'POST':
            product_form = ProductForm(request.POST)
            # form에 image 폼 추가
            image_form = ImageForm(request.POST, request.FILES)
            tmp_images = request.FILES.getlist('image')
            
            # 상품 정보에 대한 폼과 이미지 폼이 유효하면
            if product_form.is_valid() and image_form.is_valid():
                product = product_form.save(commit=False)
                product.admin = request.user

                if tmp_images:
                    for img in tmp_images:
                        img_instance = Image(product=product, image=img)
                        product.save()
                        img_instance.save()

                product.save()
                return redirect('products:index')
        else:
            product_form = ProductForm()
            image_form = ImageForm()
            
        context = {
            'product_form': product_form,
            'image_form': image_form,
        }

        return render(request, 'products/create.html', context)
    
    else:
        return redirect('products:index')    # admin 아니면 index로 리다이렉트


def detail(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    product_buy_form = ProductBuyForm()
    inquiry_form = InquiryForm()
    reply_form = ReplyForm()
    inquiries = product.inquiry_set.order_by('-pk') # 문의 최신순
    reviews = product.review_set.order_by('-pk') # 리뷰 최신순
    # print(reviews[3].reviewimage_set.all())

    # model에서 hit은 default=0으로 설정했고 한 번 볼 때마다 1 증가하도록
    product.hit += 1
    product.save()


    # 문의 페이지네이션
    inquiry_page = request.GET.get('inquiry_page', '1')
    inquiry_paginator = Paginator(inquiries, 5)
    inquiry_page_obj = inquiry_paginator.get_page(inquiry_page)

    
    # 후기 페이지네이션
    review_page = request.GET.get('review_page', '1')
    review_paginator = Paginator(reviews, 5)
    review_page_obj = review_paginator.get_page(review_page)
    context = {
        'product': product,
        'image_cnt': product.image_set.count(),
        'product_buy_form': product_buy_form,
        'inquiry_form': inquiry_form,
        'reply_form': reply_form,
        'inquiries': inquiries,
        'inquiries': inquiry_page_obj,  # 문의 페이지네이션
        'reviews': review_page_obj, # 후기 페이지네이션
    }

    return render(request, 'products/detail.html', context)


def update(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    images = Image.objects.filter(product_id=product_pk)
    
    # 요청한 user의 is_superuser가 1이면(admin이면)
    if request.user.is_superuser == 1:
        if request.method == 'POST':
            product_form = ProductForm(request.POST, instance=product)
            image_form = ImageForm(request.POST, request.FILES) 
            tmp_images = request.FILES.getlist('image') # TemporaryUploadedFile 객체 리스트

            # 기존 이미지 삭제
            for img in images:
                if img:
                    img.delete()

            # 상품 정보 폼과 이미지 폼이 유효하면
            if product_form.is_valid() and image_form.is_valid():
                product = product_form.save(commit=False)

                if tmp_images:
                    for img in tmp_images:
                        img_instance = Image(product=product, image=img)
                        product.save()
                        img_instance.save()

                product.save()
                # 상품 상세 보기 페이지로
                return redirect('products:detail', product_pk)
        
        else:
            product_form = ProductForm(instance=product)
            if images:
                image_form = ImageForm(instance=images[0])
            else:
                image_form = ImageForm()
            
        context = {
            'product_form': product_form,
            'image_form': image_form,
        }

        return render(request, 'products/create.html', context)
    
    else:
        return redirect('products:detail', product_pk) 


# 찜
def ddib(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    ddib = Ddib.objects.get(user=request.user) # user와 ddib 1:1
    ddib_items = ddib.ddibitem_set.all()
    # print(ddib_items[0])

    for item in ddib_items: # 
        if product == item.product:
            item.delete() # 찜 목록에서 item을 지우고
            is_ddib = False
            break

    else: # 찜한 상태가 아니라면
        DdibItem.objects.create(ddib=ddib, product=product)
        is_ddib = True
    context = {
        "is_ddib": is_ddib
        }
    # return redirect('products:detail', product_pk)
    return JsonResponse(context)

@login_required
def cart(request, product_pk):
    product = Product.objects.get(pk=product_pk)

    # 유저 회원가입 시 장바구니가 자동으로 생성됨.
    # 로그인 한 유저면 카트 인스턴스를 생성함.
    cart = Cart.objects.get(user=request.user)

    does_exist = False
    
    if request.method == 'POST':
        # 구매 수량 입력 후 장바구니
        product_buy_form = ProductBuyForm(request.POST)

        if product_buy_form.is_valid():
            form = product_buy_form.save(commit=False)

            cart_items = cart.cartitem_set.all()

            # 이미 같은 상품이 있으면, 수량 추가
            for item in cart_items:
                if product == item.product:
                    item.quantity += form.quantity
                    item.save()
                    does_exist = True
                    break
            else:
                CartItem.objects.create(cart=cart, product=product, quantity=form.quantity)

    data = {
        'doesExist': does_exist,
    }

    return JsonResponse(data)


# 후기 작성
@login_required
def review_create(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        # form에 review_image 폼 추가
        review_image_form = ReviewImageForm(request.POST, request.FILES)
        tmp_img = request.FILES.getlist('review_img')
                
        # 리뷰 작성에 대한 폼과 이미지 폼이 유효하면
        if review_form.is_valid() and review_image_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.product = product

            if tmp_img:
                for img in tmp_img:
                    img_instance = ReviewImage(review=review, review_img=img)
                    review.save()
                    img_instance.save()

            review.save()
            # messages.success(request, '후기가 정상적으로 수정되었습니다..')
            return redirect('products:detail', product_pk)
    else:
        review_form = ReviewForm()
        review_image_form = ReviewImageForm()
                
    context = {
        'review_form': review_form,
        'review_image_form': review_image_form
    }

    return render(request, 'products/review.html', context)

# 후기 수정
@login_required
def review_update(request, product_pk, review_pk):
    product = Product.objects.get(pk=product_pk)
    review = get_object_or_404(Review, pk=review_pk)

    review_images = ReviewImage.objects.filter(pk=review_pk)

    if request.user == review.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, instance=review)
            # form에 review_image 폼 추가
            review_image_form = ReviewImageForm(request.POST, request.FILES)
            tmp_img = request.FILES.getlist('review_img')
                    
            for img in review_images:
                if img:
                    img.delete()

            # 리뷰 작성에 대한 폼과 이미지 폼이 유효하면
            if review_form.is_valid() and review_image_form.is_valid():
                review = review_form.save(commit=False)

                review.user = request.user
                review.product = product

                if tmp_img:
                    for img in tmp_img:
                        img_instance = ReviewImage(review=review, review_img=img)
                        review.save()
                        img_instance.save()

                review.save()
                # messages.success(request, '후기 수정이 완료되었습니다.')
                # 후기 목록이 포함된 상품 상세 보기 페이지로
                return redirect('products:detail', product_pk)
        else:
            review_form = ReviewForm(instance=review)
            if review_images:
                review_image_form = ReviewImageForm(instance=review_images[0])
            else:
                review_image_form = ReviewImageForm()
            
        context = {
            'review_form': review_form,
            'review_image_form': review_image_form,
            'review': review,
        }

        return render(request, 'products/review_update.html', context)
    
    else:

products/templates/products/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<section class="container" style="width: 640px;height: 1315px; margin-top: 50px;">
<div class="container my-5">
  {% if request.resolver_match.url_name == 'create' %}
  <h1 class="mb-5 text-center" style='color:#5e0080;'>판매 상품 등록</h1>
  {% else %}
  <h1 class="mb-5 text-center" style='color:#5e0080;'>판매 상품 수정</h1>
  {% endif %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form product_form %}
    {% bootstrap_form image_form %}

    <div class="text-end">
      {% if request.resolver_match.url_name == 'create' %}
      <input type="submit" value="등록" style='background-color: #5e0080; border-color: #5e0080; color:white' class="btn btn-primary">
      {% else %}
      <input type="submit" value="수정" style='background-color: #5e0080; border-color: #5e0080; color:white' class="btn btn-primary">
      {% endif %}
    </div>
  </form>
</div>
</section>
{% endblock content %}

products/templates/products/review.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<div class="container my-5" style="width: 1070px; padding-bottom: 100px;">
    <div style="box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 0px;">
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="">
                <svg viewbox="0 0 1440 320" xmlns="http://www.w3.org/2000/svg">
                    <defs>
                        <style type="text/css">
                            .wave {
                                animation: wave 8s linear infinite;
                                transform: rotate(180deg);
                            }

                            .wave1 {
                                animation: wave1 10s linear infinite;
                                transform: rotate(180deg);
                            }

                            .wave2 {
                                animation: wave2 12s linear infinite;
                                transform: rotate(180deg);
                            }

                            @keyframes wave {
                                0% {
                                    transform: translateX(0%);
                                }

                                100% {
                                    transform: translateX(100%);
                                }
                            }

                            @keyframes wave1 {
                                0% {
                                    transform: scaleY(1.2) translateX(0%);
                                }

                                100% {
                                    transform: scaleY(1.2) translateX(100%);
                                }
                            }

                            @keyframes wave2 {
                                0% {
                                    transform: scaleY(.8) translateX(0%);
                                }

                                100% {
                                    transform: scaleY(.8) translateX(100%);
                                }
                            }
                        </style>
                        <path id='sineWave' fill="#5e0080" fill-opacity="0.5"
                            d="M0,160 C320,300,420,300,740,160 C1060,20,1120,20,1440,160 V0 H0" />
                    </defs>
                    <use class="wave" href="#sineWave" />
                    <use class="wave" x="-100%" href="#sineWave" />
                    <use class="wave1" href="#sineWave" />
                    <use class="wave1" x="-100%" href="#sineWave" />
                    <use class="wave2" href="#sineWave" />
                    <use class="wave2" x="-100%" href="#sineWave" />
                </svg>
            </div>
            <div class="p-5">
                {% csrf_token %}
                <div class=" d-flex justify-content-end">
                    <input class="btn" style="color: #5e0080; font-weight: 600;" type="submit" value="작성완료"></input>
                </div>
                <h2><input class="input-title form-control mb-3" style="border:0px; font-size: 1.5rem;" name="title"
                        placeholder="제목을 입력해주세요." value="{{ article.title }}"></h2>
                <hr>
                <textarea rows="18" cols="10" class="form-control my-3" style="border:0px" name="content"
                    placeholder="ㆍ 작성하신 후기는 치킨컬리 이용자에게 공개됩니다.&#13;&#10;&#13;&#10;ㆍ후기 작성 시 1,000원의 적립금을 영업일 기준 2일 전후로 지급합니다.&#13;&#10;&#13;&#10;ㆍ후기 도용 시 적립금 2배 회수, 1년간 커뮤니티 이용 제한, 3개월간 후기 적립금 지급이 중단됩니다.">{{ article.content }}</textarea>
                <input type="file" name="review_img" multiple="" accept="image/*" class="form-control"
                    id="id_review_img">
        </form>
    </div>
</div>
<!-- <div class='container py-3'>
    <div style='float:left'>
        <h5 class='fw-bolder'>{{ product.product_name }}</h5>
    </div>
    <form action="" method="POST" enctype="multipart/form-data" class='form-label mt-3'>
        {% csrf_token %}
        {% bootstrap_form review_form %}
        {% bootstrap_form review_image_form %}
        <div class="d-flex justify-content-center my-3">
            <input type="submit" class="btn py-2 px-5 fw-bold form-control"
                style="border-radius:0px; height:56px; background-color: #5e0080; color: white" value="등록하기">
        </div>
    </form>
</div> -->
{% endblock %}

products/templates/products/review_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<div class="container my-5" style="width: 1070px; padding-bottom: 100px;">
  <div style="box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 0px;  margin-bottom: 100px;">
    <form action="" method="POST" enctype="multipart/form-data">
      <div class="">
        <svg viewbox="0 0 1440 320" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <style type="text/css">
              .wave {
                animation: wave 8s linear infinite;
                transform: rotate(180deg);
              }

              .wave1 {
                animation: wave1 10s linear infinite;
                transform: rotate(180deg);
              }

              .wave2 {
                animation: wave2 12s linear infinite;
                transform: rotate(180deg);
              }

              @keyframes wave {
                0% {
                  transform: translateX(0%);
                }

                100% {
                  transform: translateX(100%);
                }
              }

              @keyframes wave1 {
                0% {
                  transform: scaleY(1.2) translateX(0%);
                }

                100% {
                  transform: scaleY(1.2) translateX(100%);
                }
              }

              @keyframes wave2 {
                0% {
                  transform: scaleY(.8) translateX(0%);
                }

                100% {
                  transform: scaleY(.8) translateX(100%);
                }
              }
            </style>
            <path id='sineWave' fill="#5e0080" fill-opacity="0.5"
              d="M0,160 C320,300,420,300,740,160 C1060,20,1120,20,1440,160 V0 H0" />
          </defs>
          <use class="wave" href="#sineWave" />
          <use class="wave" x="-100%" href="#sineWave" />
          <use class="wave1" href="#sineWave" />
          <use class="wave1" x="-100%" href="#sineWave" />
          <use class="wave2" href="#sineWave" />
          <use class="wave2" x="-100%" href="#sineWave" />
        </svg>
      </div>
      <div class="p-5">
        {% csrf_token %}
        <div class=" d-flex justify-content-end">
          <input class="btn" style="color: #5e0080; font-weight: 600;" type="submit" value="수정하기">
        </div>
        <h2><input class="input-title form-control mb-3" style="border:0px; font-size: 1.5rem;" name="title"
            placeholder="제목을 입력해주세요." value="{{ review.title }}" maxlength="20" required></h2>
        <hr>
        <textarea rows="18" cols="10" class="form-control my-3" style="border:0px" name="content"
          required>{{ review.content }}</textarea>
        <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
    </form>
  </div>
</div>

{% endblock content %}